import { AxiosResponse } from 'axios';
import { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Tabs from '../components/Tabs';
import { fetchCategories } from '../http';
import { ICategory, ICollectionResponse } from '../types';

interface IProptype {
  categories: {
    items: ICategory[];
  };
}

const Home: NextPage<IProptype> = ({ categories }) => {
  return (
    <div>
      <Head>
        <title>Taushik's Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Tabs categories={categories.items} />

      <main>
        <h1 className='mx'>welcome to hell</h1>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();

  console.log(categories);

  return {
    props: {
      categories: {
        items: categories.data,
      },
    },
  };
};

export default Home;
